### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by txtsd** [PrismLauncher/changelog-generator#5]
```
λ poetry run changelog-generator https://github.com/PrismLauncher/PrismLauncher.git 7.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/txtsd/git/prismlauncher/changelog-generator/changelog_generator/__main__.py", line 145, in main
    generate(args.repo, args.milestone, token)
  File "/home/txtsd/git/prismlauncher/changelog-generator/changelog_generator/__main__.py", line 102, in generate
    repo = g.get_repo(repo_name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/txtsd/.cache/pypoetry/virtualenvs/changelog-generator-ynheKdeS-py3.11/lib/python3.11/site-packages/github/MainClass.py", line 363, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/txtsd/.cache/pypoetry/virtualenvs/changelog-generator-ynheKdeS-py3.11/lib/python3.11/site-packages/github/Requester.py", line 442, in requestJsonAndCheck
    return self.__check(
           ^^^^^^^^^^^^^
  File "/home/txtsd/.cache/pypoetry/virtualenvs/changelog-generator-ynheKdeS-py3.11/lib/python3.11/site-packages/github/Requester.py", line 487, in __check
    raise self.__createException(status, responseHeaders, data)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by Scrumplex** [comment]
It has to be `PrismLauncher/PrismLauncher`. Also, I am sure 7.2 won't work as we might not have all the necessary labels there. Try 8.0

**Comment by txtsd** [comment]
Threw an assertion error, but the code works. Thanks!
